### ISSUE TITLE
AndroidManifest.xml:44: AAPT: error: resource style/AppTheme not found

### ISSUE THREAD

**Issue by 1N50MN14** [douglaszaltron/cordova-plugin-window-background#1]
Hi @douglaszaltron thanks for the plugin exactly what I've been looking for!

Unfortunately the project fails to build and throws the error `AndroidManifest.xml:44: AAPT: error: resource style/AppTheme not found` with the latest cordova-android (7.0.0) - any ideas how to resolve this?

Thank you

**Comment by marcusforsberg** [comment]
Hi @1N50MN14, if you're still looking for a solution for this, we've pushed a fix to our variant of this plugin here: https://github.com/winteragency/cordova-plugin-android-window-background

**Comment by 1N50MN14** [comment]
supert! tack @marcusforsberg!

**Comment by douglaszaltron** [comment]
Closed due to inactivity. Comment or open a new issue if you need further assistance :)
